name       : sl
version    : 5.02
release    : 1
source     :
    - https://github.com/mtoyoda/sl/archive/5.02.tar.gz : 1e5996757f879c81f202a18ad8e982195cf51c41727d3fea4af01fdcbbb5563a
license    : Custom 
component  : system.util
summary    : SL (Steam Locomotive) runs across your terminal when you type "sl" as you meant to type "ls".
description: |
    SL (Steam Locomotive) runs across your terminal when you type "sl" as you meant to type "ls". It's just a joke command, and not useful at all.
build      : |
    %make
install    : |
    install -D -m 00755 sl $installdir/usr/bin/sl
    install -D -m 00644 sl.1 $installdir/usr/share/man/man1/sl.1
    install -D -m 00644 LICENSE $installdir/usr/share/licenses/sl/LICENSE